name: cli-tutorial-javi-app
language: Python
variables:
  - name: output
    inputType: OutputTopic
    defaultValue: f1-data
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: demo-data-source
